// 사용법: https://www.jetbrains.com/help/webstorm/http-client-in-product-code-editor.html

### GET
GET http://localhost:3000/person

<> 2026-04-09T145838.200.json

### POST
POST http://localhost:3000/person
Content-Type: application/json

{
  "name": "조익희",
  "age": 28,
  "email": "ikhee@naver.com"
}

<> 2026-04-09T145830.200.json